apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod
  labels:
    app: myapp

spec: 
  container: 
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerport: 80